import SwiftUI

struct AreaCard: View {
    let area: AreaSummary

    @Environment(FavoritesService.self) private var favorites
    @Environment(ProgressService.self) private var progress
    @Environment(AreaDataService.self) private var areas
    @Environment(AreaSilhouetteService.self) private var silhouettes
    @Environment(LocationService.self) private var location
    @AppStorage(StorageKeys.units) private var units: UnitsPreference = .imperial

    private var cachedArea: Area? { areas.cachedArea(id: area.id) }

    /// Great-circle distance from user to area centroid, in miles.
    /// Used for the "X mi away" caption on the card. Returns nil when
    /// user location is unknown.
    private var distanceMi: Double? {
        guard let loc = location.userLocation else { return nil }
        let R = 3958.8
        let dLat = (area.centerLat - loc.latitude) * .pi / 180
        let dLon = (area.centerLon - loc.longitude) * .pi / 180
        let h = sin(dLat / 2) * sin(dLat / 2)
            + cos(loc.latitude * .pi / 180) * cos(area.centerLat * .pi / 180)
            * sin(dLon / 2) * sin(dLon / 2)
        return R * 2 * atan2(sqrt(h), sqrt(1 - h))
    }

    /// Prefer the cached area's runtime-computed silhouette so per-line
    /// difficulty colors match what the user sees inside AreaView. The
    /// R2-hosted silhouette is generated by a separate Python script
    /// that drifts behind upstream OSM data — Shadow Mountain rendered
    /// as all-easy from the script's output but had a real mix once
    /// iOS fetched the live data, for example. Falls back to the
    /// pre-rendered silhouette while the per-area cache is cold.
    ///
    /// `cachedSilhouette` is a non-blocking sync read; the `.task`
    /// modifier on the artwork view triggers the actual R2 load when
    /// the card appears, and SwiftUI re-renders once the silhouette
    /// service publishes the loaded data.
    private var effectiveSilhouette: AreaSilhouette? {
        if let cached = cachedArea, !cached.trails.isEmpty {
            // Memoized by AreaDataService — this used to rebuild the whole
            // silhouette from trail geometry on every read, and it is read
            // twice per card body.
            let computed = areas.computedSilhouette(for: cached)
            if !computed.l.isEmpty { return computed }
        }
        return silhouettes.cachedSilhouette(for: area.id)
    }

    /// Filter by the cached area's current trail IDs so orphan completions
    /// from a prior buggy state (e.g. trails whose count-suffix IDs got
    /// scrambled by a silent re-fetch before the determinism fix landed)
    /// don't inflate the count. Falls back to unfiltered when the area
    /// hasn't been hydrated yet so the card isn't stuck at 0 pre-prefetch.
    private var completedCount: Int {
        if let trails = cachedArea?.trails, !trails.isEmpty {
            // Credit duplicate-area twins by geometry, so the same completed
            // trails that show a checkmark inside also count here (0/77 under a
            // twin was the "my completion disappeared" report).
            return progress.completionCount(in: area.id, trails: trails)
        }
        return progress.completionCount(in: area.id)
    }
    private var totalTrails: Int { cachedArea?.resolvedTrailCount ?? area.trailCount ?? 0 }

    private var progressFraction: Double {
        guard totalTrails > 0 else { return 0 }
        return Double(completedCount) / Double(totalTrails)
    }

    /// Easy / moderate / hard share of this area's trail lines. Reads the
    /// effective silhouette, which is the cached area's recomputation when
    /// available so the bar reflects current trail data instead of stale
    /// bundle output. Returns nil when no silhouette is available.
    private var difficultyMix: (easy: Double, moderate: Double, hard: Double)? {
        guard let silhouette = effectiveSilhouette else { return nil }
        var counts = (e: 0, m: 0, h: 0)
        for line in silhouette.l {
            switch line.d {
            case "e": counts.e += 1
            case "m": counts.m += 1
            case "h": counts.h += 1
            default:  break
            }
        }
        let total = counts.e + counts.m + counts.h
        guard total > 0 else { return nil }
        return (
            Double(counts.e) / Double(total),
            Double(counts.m) / Double(total),
            Double(counts.h) / Double(total)
        )
    }

    var body: some View {
        ZStack(alignment: .bottomLeading) {
            // 176 (not 160) so the heart button and the info box can't
            // collide: the box grows upward from the bottom and its top
            // reaches ~y63 with every row present; the heart occupies
            // y10–50. At 160 they overlapped in the top-right corner.
            artwork
                .frame(width: 220, height: 176)
                .clipShape(RoundedRectangle(cornerRadius: 20, style: .continuous))

            // Zero stack spacing: the rows should read as one tight
            // block under the name. Even at spacing 2 the name-to-
            // subtitle gap read as "too much space" on device — what
            // remains is the fonts' own line padding, so the subtitle
            // row pulls up an extra point into the headline's descender
            // zone, and only the bars get explicit breathing room.
            VStack(alignment: .leading, spacing: 0) {
                Text(area.name)
                    .font(.headline)
                    .foregroundStyle(.primary)
                    .lineLimit(1)

                HStack(spacing: 6) {
                    Text(area.subtitle)
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    if totalTrails > 0 {
                        Text("·")
                            .foregroundStyle(.tertiary)
                        Text("\(completedCount)/\(totalTrails) trails")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
                .padding(.top, -1)

                // The distance line and difficulty bar load ASYNC (user
                // location / R2 silhouette). Always render their slots —
                // with placeholders while empty — so the glass box's
                // height never changes after first layout. On iOS 26 the
                // Liquid Glass shape doesn't reliably re-invalidate when
                // its content grows, so a box that gained rows mid-life
                // left the last row (the progress bar) hanging outside
                // the glass edge.
                Text(distanceMi.map { "\(UnitFormatter.distance(miles: $0, units: units)) away" } ?? " ")
                    .font(.caption2)
                    .foregroundStyle(.secondary)

                Group {
                    if let mix = difficultyMix {
                        DifficultyMixBar(mix: mix)
                    } else {
                        Color.clear
                    }
                }
                .frame(height: 3)
                .padding(.top, 3)

                if totalTrails > 0 {
                    ProgressView(value: progressFraction)
                        .tint(.accentColor)
                        .padding(.top, 3)
                }
            }
            .padding(.horizontal, 14)
            // Asymmetric: slimmer on top so the box's TOP EDGE sits
            // lower (more artwork visible), fuller on the bottom so the
            // progress bar doesn't crowd the glass edge.
            .padding(.top, 7)
            .padding(.bottom, 10)
            // 208, NOT the artwork's 220: the inset paddings below place
            // the box 6pt inside each side edge, so a 220-wide box had a
            // 232-wide footprint and its right edge stuck out 6pt past
            // the artwork. 208 + 6pt margins = exactly the 220 card.
            .frame(width: 208, alignment: .leading)
            .compatibleGlass(in: RoundedRectangle(cornerRadius: 16, style: .continuous))
            .padding(.horizontal, 6)
            .padding(.top, 6)
            // 4 (not 6): hugging the card's bottom edge shifts the whole
            // box down, which is where it should sit — the artwork above
            // is the star.
            .padding(.bottom, 4)
        }
        // The artwork is a fixed 220×176 — larger text sizes grow the
        // info box up into the heart button and out of the card. Cap
        // type inside the card only (at the default size, so card text
        // simply doesn't scale); the surrounding screen scales freely.
        .dynamicTypeSize(...DynamicTypeSize.large)
        .overlay(alignment: .topTrailing) {
            Button {
                Task { await favorites.toggle(areaId: area.id) }
            } label: {
                Image(systemName: favorites.isFavorite(area.id) ? "heart.fill" : "heart")
                    .foregroundStyle(favorites.isFavorite(area.id) ? .red : .primary)
                    .padding(10)
                    .compatibleGlass(in: .circle)
            }
            // Equal insets so the heart sits symmetrically in the
            // corner. (An earlier top-biased 10/18 split read as
            // "closer to the top than the right" on device; the taller
            // 176pt card no longer needs the upward bias it was
            // compensating for.)
            .padding(.top, 12)
            .padding(.trailing, 12)
        }
    }

    @ViewBuilder
    private var artwork: some View {
        Group {
            if let silhouette = effectiveSilhouette {
                SilhouetteArtwork(silhouette: silhouette)
            } else {
                LinearGradient(
                    colors: gradientColors,
                    startPoint: .topLeading,
                    endPoint: .bottomTrailing
                )
            }
        }
        // Kick the R2 fetch when the card first appears (or when it
        // recycles onto a new area id during scroll). The service
        // dedupes in-flight requests, so HomeView.prefetchVisibleAreas
        // racing this `.task` is fine — only one network call happens.
        // SwiftUI re-renders the card once the service's @Observable
        // store publishes the loaded silhouette.
        .task(id: area.id) {
            await silhouettes.silhouette(for: area.id)
        }
    }

    private var gradientColors: [Color] {
        let palette: [[Color]] = [
            [.green, .teal],
            [.blue, .indigo],
            [.orange, .red],
            [.purple, .blue],
            [.teal, .green],
        ]
        let index = abs(area.id.hashValue) % palette.count
        return palette[index]
    }
}

private struct DifficultyMixBar: View {
    let mix: (easy: Double, moderate: Double, hard: Double)

    var body: some View {
        GeometryReader { geo in
            HStack(spacing: 0) {
                if mix.easy > 0 {
                    Color.green.frame(width: geo.size.width * mix.easy)
                }
                if mix.moderate > 0 {
                    Color.orange.frame(width: geo.size.width * mix.moderate)
                }
                if mix.hard > 0 {
                    Color.red.frame(width: geo.size.width * mix.hard)
                }
            }
        }
        .clipShape(Capsule())
    }
}

private struct SilhouetteArtwork: View {
    let silhouette: AreaSilhouette

    @Environment(\.colorScheme) private var colorScheme

    var body: some View {
        ZStack {
            // Adaptive backdrop. Reads ~black in dark mode and a soft light
            // gray in light mode so the card has elevation against the
            // parent's primary background without being a harsh black brick.
            Color(.secondarySystemBackground)

            // Glow halo only reads well over the dark backdrop — in light
            // mode it muddies the trail lines without adding the neon-on-
            // black depth we get in dark mode.
            if colorScheme == .dark {
                SilhouetteCanvas(silhouette: silhouette, lineWidth: 5, opacity: 0.45)
                    .blur(radius: 5)
            }

            SilhouetteCanvas(silhouette: silhouette, lineWidth: 1.6, opacity: 1.0)
        }
        .overlay(
            // Subtle border so the card has a defined edge in both modes,
            // especially when the artwork lines are sparse.
            RoundedRectangle(cornerRadius: 20, style: .continuous)
                .stroke(Color(.separator), lineWidth: 0.5)
        )
    }
}

private struct SilhouetteCanvas: View {
    let silhouette: AreaSilhouette
    let lineWidth: CGFloat
    let opacity: Double

    /// Draw order (harder difficulty on top), sorted ONCE at init instead of
    /// inside the Canvas closure on every redraw. In dark mode each card renders
    /// two of these (glow + main), so the per-draw sort ran twice per card.
    private let ordered: [SilhouetteLine]

    init(silhouette: AreaSilhouette, lineWidth: CGFloat, opacity: Double) {
        self.silhouette = silhouette
        self.lineWidth = lineWidth
        self.opacity = opacity
        self.ordered = silhouette.l.sorted {
            let pa = $0.d == "h" ? 2 : ($0.d == "m" ? 1 : 0)
            let pb = $1.d == "h" ? 2 : ($1.d == "m" ? 1 : 0)
            return pa < pb
        }
    }

    var body: some View {
        Canvas { context, size in
            guard let bbox = silhouette.bbox else { return }
            let pad: CGFloat = 12
            let drawW = size.width - 2 * pad
            let drawH = size.height - 2 * pad
            guard drawW > 0, drawH > 0 else { return }

            // Equirectangular projection with longitude scaled by cos(centerLat)
            // so trails don't look horizontally stretched.
            let centerLat = (bbox.s + bbox.n) / 2
            let lonScale = cos(centerLat * .pi / 180)
            let xRange = max((bbox.e - bbox.w) * lonScale, .leastNonzeroMagnitude)
            let yRange = max(bbox.n - bbox.s, .leastNonzeroMagnitude)
            let scale = min(drawW / xRange, drawH / yRange)
            let canvasW = xRange * scale
            let canvasH = yRange * scale
            let xOffset = pad + (drawW - canvasW) / 2
            let yOffset = pad + (drawH - canvasH) / 2

            // `ordered` is sorted once at init (harder color wins where trails
            // cross), not per redraw.
            for line in ordered {
                guard line.p.count >= 2 else { continue }
                var path = Path()
                for (i, pt) in line.p.enumerated() {
                    guard pt.count >= 2 else { continue }
                    let lat = pt[0], lon = pt[1]
                    let x = xOffset + (lon - bbox.w) * lonScale * scale
                    // Flip y because lat grows up, screen y grows down.
                    let y = yOffset + canvasH - (lat - bbox.s) * scale
                    let p = CGPoint(x: x, y: y)
                    if i == 0 { path.move(to: p) } else { path.addLine(to: p) }
                }
                context.stroke(
                    path,
                    with: .color(color(for: line.d).opacity(opacity)),
                    style: StrokeStyle(lineWidth: lineWidth, lineCap: .round, lineJoin: .round)
                )
            }
        }
    }

    private func color(for difficulty: String) -> Color {
        switch difficulty {
        case "e": return .green
        case "m": return .orange
        case "h": return .red
        default:  return .gray
        }
    }
}
